testsuite: Run all tests even when one is failing.

diff --git a/testsuite b/testsuite
--- a/testsuite
+++ b/testsuite
@@ -200,14 +200,23 @@ for U in $PG_UMASKS; do
     for T; do
         TBASE=${T##*/}
         [ "${FROM:-}" ] && [ "${TBASE%%_*}" -lt "${FROM:-}" ] && continue
-        echo "=== Running test $TBASE ... ==="
+        echo "### PostgreSQL test $TBASE ###"
         perl -I. $T || {
             EXIT=$?
+            FAILED_TESTS="${FAILED_TESTS:-} $T"
             if [ "${FAILURE:-}" ]; then
                 echo "*** $TBASE failed with status $EXIT, dropping you into a shell in the testbed ***"
                 ${SHELL:-/bin/sh}
             fi
-            exit $EXIT
         }
+        echo "### End test $TBASE ###"
+        echo
     done
 done
+
+if [ "${FAILED_TESTS:-}" ]; then
+    echo "Failed tests: $FAILED_TESTS"
+    echo
+fi
+
+exit ${EXIT:-0}
